# Generated by Django 4.2.7 on 2026-06-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-building')", max_length=50, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code (e.g., #007bff)', max_length=7)),
                ('max_booking_duration', models.PositiveIntegerField(blank=True, help_text='Maximum booking duration in hours', null=True)),
                ('min_booking_duration', models.PositiveIntegerField(blank=True, help_text='Minimum booking duration in hours', null=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='Does this category require admin approval for bookings?')),
                ('booking_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional fee for bookings in this category', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category for this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='bookings.category'),
        ),
    ]
