# Generated by Django 4.2.7 on 2026-06-23 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0005_category_resource_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pictures/')),
                ('website', models.URLField(blank=True, help_text='Your personal website or portfolio', null=True)),
                ('twitter', models.CharField(blank=True, help_text='Twitter username', max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, help_text='LinkedIn username', max_length=50, null=True)),
                ('github', models.CharField(blank=True, help_text='GitHub username', max_length=50, null=True)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('booking_reminders', models.BooleanField(default=True, help_text='Receive booking reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
