# Generated by Django 4.2.7 on 2026-06-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingpayment_discountcode_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookingPayment',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
