# Generated by Django 4.2.7 on 2026-06-25 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0014_equipment_equipmentcategory_maintenancerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/created this equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['owner'], name='bookings_eq_owner_i_3a167f_idx'),
        ),
    ]
