# Generated by Django 4.2.7 on 2026-06-25 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0016_savedsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of reservation')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment', 'status'], name='bookings_eq_equipme_93b863_idx'), models.Index(fields=['user', 'status'], name='bookings_eq_user_id_e5feb2_idx'), models.Index(fields=['start_date', 'end_date'], name='bookings_eq_start_d_430d85_idx'), models.Index(fields=['expires_at'], name='bookings_eq_expires_74d506_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='equipmentreservation',
            constraint=models.UniqueConstraint(fields=('equipment', 'start_date', 'end_date'), name='unique_reservation_slot'),
        ),
    ]
