# Generated by Django 4.2.7 on 2026-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_meetingroom_floor_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='room_photo',
        ),
        migrations.AlterField(
            model_name='category',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_booking_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_booking_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='MeetingRoom',
        ),
    ]
