# Generated by Django 4.2.7 on 2026-06-28 19:52

import bookings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_remove_meetingroom_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='floor_plan',
            field=models.ImageField(blank=True, help_text='Upload a floor plan of the room', null=True, upload_to='floor_plans/', validators=[bookings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='resource',
            name='room_photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of the room', null=True, upload_to='room_photos/', validators=[bookings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='category',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional fee for bookings in this category', max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code (e.g., #007bff)', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-building')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_booking_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum booking duration in hours', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_booking_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum booking duration in hours', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Does this category require admin approval for bookings?'),
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('floor_number', models.IntegerField(default=1)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seating_capacity', models.IntegerField(default=0, help_text='Seating capacity')),
                ('standing_capacity', models.IntegerField(default=0, help_text='Standing capacity')),
                ('classroom_capacity', models.IntegerField(default=0, help_text='Classroom setup capacity')),
                ('theater_capacity', models.IntegerField(default=0, help_text='Theater setup capacity')),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_video_conferencing', models.BooleanField(default=False)),
                ('has_phone', models.BooleanField(default=False)),
                ('has_smart_tv', models.BooleanField(default=False)),
                ('has_audio_system', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_air_conditioning', models.BooleanField(default=True)),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible')),
                ('room_size_sqft', models.IntegerField(blank=True, help_text='Room size in square feet', null=True)),
                ('natural_light', models.BooleanField(default=False)),
                ('has_window', models.BooleanField(default=True)),
                ('default_setup_time', models.IntegerField(default=15, help_text='Default setup time in minutes')),
                ('default_teardown_time', models.IntegerField(default=15, help_text='Default teardown time in minutes')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='floor_plans/', validators=[bookings.models.validate_image_size])),
                ('room_photo', models.ImageField(blank=True, null=True, upload_to='room_photos/', validators=[bookings.models.validate_image_size])),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the room')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='meeting_rooms', to='bookings.amenity')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room', to='bookings.resource')),
            ],
        ),
    ]
