# Generated by Django 5.2.15 on 2026-07-03 11:16

import bookings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_amenity_resource_floor_plan_resource_room_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Equipment Categories'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='room_photo',
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Last activity timestamp', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='maintenance_alerts',
            field=models.BooleanField(default=True, help_text='Receive maintenance alerts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rental_reminders',
            field=models.BooleanField(default=True, help_text='Receive rental reminders'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reservation_notifications',
            field=models.BooleanField(default=True, help_text='Receive reservation notifications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pictures/', validators=[bookings.models.validate_image_size]),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'start_time'], name='bookings_bo_custome_b686e7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='bookings_ca_slug_596bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['owner', 'status'], name='bookings_eq_owner_i_9b407c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category', 'status'], name='bookings_eq_categor_efce22_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status'], name='bookings_re_status_cc35e4_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category'], name='bookings_re_categor_013932_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['owner', 'status'], name='bookings_re_owner_i_2db8a3_idx'),
        ),
    ]
