# Generated by Django 5.2.15 on 2026-07-05 21:28

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_alter_equipmentcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an equipment photo (max 5MB)', upload_to='equipment/gallery/', validators=[bookings.models.validate_image_size])),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary image for this equipment')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of the equipment (max 5MB)', null=True, upload_to='equipment/', validators=[bookings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: Link to an external image URL', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail', null=True, upload_to='equipment/thumbnails/'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['image'], name='bookings_eq_image_b76227_idx'),
        ),
        migrations.AddField(
            model_name='equipmentimage',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='bookings.equipment'),
        ),
        migrations.AddIndex(
            model_name='equipmentimage',
            index=models.Index(fields=['equipment', 'is_primary'], name='bookings_eq_equipme_831303_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentimage',
            index=models.Index(fields=['order'], name='bookings_eq_order_cd3ee4_idx'),
        ),
    ]
